export default [
  { name: "Blue violet", slug: "blueviolet", color: "#8a2be2" },
  { name: "Cadet blue", slug: "cadetblue", color: "#5f9ea0" },
  { name: "Chocolate", slug: "chocolate", color: "#d2691e" },
  { name: "Crimson", slug: "crimson", color: "#dc143c" },
  { name: "Dark cyan", slug: "darkcyan", color: "#008b8b" },
  { name: "Dark goldenrod", slug: "darkgoldenrod", color: "#b8860b" },
  { name: "Darkolive green", slug: "darkolivegreen", color: "#556b2f" },
  { name: "Dark orchid", slug: "darkorchid", color: "#9932cc" },
  { name: "Dark violet", slug: "darkviolet", color: "#9400d3" },
  { name: "Deep pink", slug: "deeppink", color: "#ff1493" },
  { name: "Dodger blue", slug: "dodgerblue", color: "#1e90ff" },
  { name: "Fire brick", slug: "firebrick", color: "#b22222" },
  { name: "Forest green", slug: "forestgreen", color: "#228b22" },
  { name: "Green", slug: "green", color: "#008000" },
  { name: "Medium purple", slug: "mediumpurple", color: "#9370db" },
  { name: "Medium slate blue", slug: "mediumslateblue", color: "#7b68ee" },
  { name: "Medium violet red", slug: "mediumvioletred", color: "#c71585" },
  { name: "Olive", slug: "olive", color: "#808000" },
  { name: "Olive drab", slug: "olivedrab", color: "#6b8e23" },
  { name: "Orangered", slug: "orangered", color: "#ff4500" },
  { name: "Pale violet red", slug: "palevioletred", color: "#db7093" },
  { name: "Rebecca purple", slug: "rebeccapurple", color: "#663399" },
  { name: "Red", slug: "red", color: "#ff0000" },
  { name: "Rosy brown", slug: "rosybrown", color: "#bc8f8f" },
  { name: "Royalblue", slug: "royalblue", color: "#4169e1" },
  { name: "Sea green", slug: "seagreen", color: "#2e8b57" },
  { name: "Sienna", slug: "sienna", color: "#a0522d" },
  { name: "Slate blue", slug: "slateblue", color: "#6a5acd" },
  { name: "Steel blue", slug: "steelblue", color: "#4682b4" },
  { name: "Teal", slug: "teal", color: "#008080" },
  { name: "Tomato", slug: "tomato", color: "#ff6347" }
];
